default_job = "clippy3"
env.CARGO_TERM_COLOR = "always"

[jobs.clippy3]
command = [
  "cargo",
  "clippy",
  "--features",
  "esp32c3",
  "--target",
  "riscv32imc-unknown-none-elf",
]
need_stdout = false

[jobs.clippy6]
command = [
  "cargo",
  "clippy",
  "--features",
  "esp32c6",
  "--target",
  "riscv32imac-unknown-none-elf",
]
env.ESP_HAL_CONFIG_FLIP_LINK = "1"
need_stdout = false

[jobs.run3]
command = [
  "cargo",
  "run",
  "--release",
  "--features",
  "esp32c3",
  "--target",
  "riscv32imc-unknown-none-elf",
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"

[jobs.run6]
command = [
  "cargo",
  "run",
  "--release",
  "--features",
  "esp32c3",
  "--target",
  "riscv32imc-unknown-none-elf",
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"

[keybindings]
c = "job:clippy3"
r = "job:run3"
