[package]
name = "esp-template"
version = "0.1.0"
edition = "2024"

[dependencies]
defmt = "1.0"
static_cell = "2.1"

[dependencies.embassy-executor]
version = "0.7"
features = ["defmt", "nightly"]

[dependencies.embassy-time]
version = "0.4"
features = ["defmt-timestamp-uptime-us"]

[dependencies.esp-backtrace]
version = "0.17"
features = [
  # "esp32c3",
  "esp32c6",
  "defmt",
  "exception-handler",
  "panic-handler",
]

[dependencies.esp-bootloader-esp-idf]
version = "0.2"
features = [
  # "esp32c3",
  "esp32c6",
  "defmt",
]

[dependencies.esp-hal]
version = "1.0.0-rc.0"
features = [
  # "esp32c3",
  "esp32c6",
  "defmt",
  "unstable",
]

[dependencies.esp-hal-embassy]
version = "0.9"
features = [
  # "esp32c3",
  "esp32c6",
  "defmt",
]

[dependencies.esp-println]
version = "0.15"
features = [
  # "esp32c3",
  "esp32c6",
  "defmt-espflash",
]
