[package]
name    = "esp-template"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[features]
default = [
  "esp-backtrace/esp32c6",
  "esp-bootloader-esp-idf/esp32c6",
  "esp-hal/esp32c6",
  "esp-println/esp32c6",
  "esp-rtos/esp32c6",
]

[dependencies]
defmt                  = "1"
esp-bootloader-esp-idf = "0.6"
static_cell            = "2"

[dependencies.embassy-executor]
version  = "0.10"
features = ["defmt"]

[dependencies.embassy-time]
version  = "0.5"
features = ["defmt-timestamp-uptime-us"]

[dependencies.esp-backtrace]
version  = "0.20"
features = ["defmt", "panic-handler"]

[dependencies.esp-hal]
version  = "1.2"
features = ["defmt", "unstable"]

[dependencies.esp-println]
version  = "0.18"
features = ["defmt-espflash"]

[dependencies.esp-rtos]
version  = "0.4"
features = ["defmt", "embassy"]

[lints]
clippy.mem_forget = "deny"
rust.unsafe_code  = "deny"
