[toolchain]
channel = "nightly-2025-09-23"
components = [
  "clippy",
  "llvm-tools",
  "rust-analyzer",
  "rust-src",
  "rustfmt",
]
targets = [
  "riscv32imac-unknown-none-elf",
  "riscv32imc-unknown-none-elf",
]
