[unstable]
build-std = ["core", "alloc", "panic_abort"]
build-std-features = ["optimize_for_size"]
codegen-backend = true

[target.'cfg(all(target_arch = "riscv32", target_os = "none"))']
runner = "espflash flash -B 115200 -M -L defmt"
rustflags = [
  "-Cforce-frame-pointers=yes",
  "-Clink-arg=--nmagic",
  "-Clink-arg=-Tlinkall.x",
  "-Clink-arg=-Tdefmt.x",

  "-Zunstable-options",
  "-Cpanic=immediate-abort",
]

[env]
DEFMT_LOG = "esp_template=info"
ESP_HAL_CONFIG_WRITE_VEC_TABLE_MONITORING = "true"

[profile.dev]
opt-level = "s"
codegen-backend = "llvm"
panic = "abort"
strip = false
debug = true

[profile.release]
opt-level = "s"
codegen-units = 1
codegen-backend = "llvm"
panic = "abort"
strip = false
debug = true
lto = true
