[unstable]
build-std = ["core", "panic_abort"]
build-std-features = ["optimize_for_size"]
codegen-backend = true

[build]
target = "riscv32imac-unknown-none-elf"

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash -B 115200 -M -L defmt"
rustflags = [
  "-Cforce-frame-pointers=yes",
  "-Clink-arg=--nmagic",
  "-Clink-arg=-Tdefmt.x",
  "-Clink-arg=-Tlinkall.x",
]

[env]
DEFMT_LOG = "info"

[profile.dev]
codegen-backend = "llvm"
[profile.release]
opt-level = "z"
codegen-units = 1
codegen-backend = "llvm"
panic = "abort"
strip = false
debug = 2
lto = true
