[unstable]
build-std = ["core", "panic_abort"]
build-std-features = ["optimize_for_size"]
codegen-backend = true

[build]
# target = "riscv32imc-unknown-none-elf" # esp32c3
target = "riscv32imac-unknown-none-elf" # esp32c6

[target.'cfg(all(target_arch = "riscv32", target_os = "none"))']
runner = "espflash flash -B 921600 -M -L defmt"
rustflags = [
  "-Cforce-frame-pointers=yes",
  "-Clink-arg=--nmagic",
  "-Clink-arg=-Tdefmt.x",
  "-Clink-arg=-Tlinkall.x",
]

[env]
DEFMT_LOG = "info"

[profile.dev]
opt-level = "z"
codegen-backend = "llvm"
debug = "line-tables-only"

[profile.release]
opt-level = "z"
codegen-units = 1
codegen-backend = "llvm"
panic = "abort"
strip = false
debug = "line-tables-only"
lto = true
