name: flake

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        output:
          - esp32c3
          - esp32c6
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: install nix
        uses: determinatesystems/nix-installer-action@v19
      - name: nix cache
        uses: determinatesystems/magic-nix-cache-action@v13
        with:
          use-flakehub: false
      - name: build flake
        run: nix build -L .#${{ matrix.output }}
