name: flake

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        output:
          - esp32c3
          - esp32c6
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size: 1G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-primary-key: "never"
      - name: build flake
        run: nix build -L .#${{ matrix.output }}
