name: flake

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        output:
          - esp32c3
          - esp32c6
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: install nix
        uses: cachix/install-nix-action@v31
      - name: build flake
        run: nix build -L .#${{ matrix.output }}
